src/checks/zcl_aoc_check_59.clas.abap, src/parsing/zcl_aoc_boolean.clas.abap, src/parsing/zcl_aoc_boolean.clas.testclasses.abap, src/parsing/zcl_aoc_boolean_tokens.clas.abap
=> issue #357, more fixes

src/checks/zcl_aoc_check_59.clas.abap, src/checks/zcl_aoc_check_59.clas.testclasses.abap, src/checks/zcl_aoc_check_59.clas.xml, src/parsing/zcl_aoc_boolean_node.clas.abap
=> #357, seems to work

src/checks/zcl_aoc_check_60.clas.abap, src/checks/zcl_aoc_check_60.clas.testclasses.abap, src/checks/zcl_aoc_check_60.clas.xml
=> string template concat, #398

src/checks/zcl_aoc_check_04.clas.abap, src/checks/zcl_aoc_super.clas.abap
=> remote enable check 04

src/checks/zcl_aoc_check_14.clas.abap
check 14: option to show only one finding per include
=> check 14: option to show only one finding per include

src/checks/zcl_aoc_check_58.clas.abap
Fix for issue #419 and performance improvements.
=> Check 58: Check for local references

src/checks/zcl_aoc_check_58.clas.abap
58: only check public methods
also see https://github.com/larshp/abapOpenChecks/pull/472
=> 58: only check public methods

src/collectors/package.devc.xml, src/collectors/zcl_aoc_embedded_packages.clas.abap, src/collectors/zcl_aoc_embedded_packages.clas.xml
Like the SAP standard, but ignores deleted objects
=> new object collector

src/checks/zcl_aoc_check_58.clas.abap
=> Issue #488

src/utils/zaoc_clones.prog.abap, src/utils/zaoc_method_length.prog.abap, src/utils/zaoc_method_length.prog.xml, src/utils/zaoc_tadir_changes.prog.abap
=> method length stats

src/checks/zcl_aoc_check_61.clas.abap, src/checks/zcl_aoc_check_61.clas.xml
=> fake package encapsulation

src/checks/zcl_aoc_check_66.clas.abap, src/checks/zcl_aoc_check_66.clas.testclasses.abap, src/checks/zcl_aoc_check_66.clas.xml
=> RAISE EXCEPTION TYPE message checks

src/checks/zcl_aoc_check_70.clas.abap, src/checks/zcl_aoc_check_70.clas.testclasses.abap
=> Fix #519 70: syntax errors

docs/_checks/45.md
Added documentation of missing expressions/functions
=> Updated documentation Check 45

src/utils/zaoc_line_length.prog.abap, src/utils/zaoc_line_length.prog.xml
option to ignore maintenance views
=> option to ignore maintenance views

src/checks/zcl_aoc_check_72.clas.abap, src/checks/zcl_aoc_check_72.clas.testclasses.abap, src/checks/zcl_aoc_check_72.clas.xml
TABL enhancement category, #540
check 72
documentation to be updated later
=> TABL enhancement category, #540

src/checks/zcl_aoc_check_58.clas.abap
=> check types, #543

docs/_checks/53.md, src/checks/zcl_aoc_check_53.clas.abap
=> issue #452

src/checks/zcl_aoc_check_70.clas.abap
=> check 70: enable rfc #521

src/checks/zcl_aoc_check_74.clas.abap, src/checks/zcl_aoc_check_74.clas.testclasses.abap, src/checks/zcl_aoc_check_74.clas.xml, src/checks/zcl_aoc_super.clas.abap
=> check for nesting, #437

docs/_checks/08.md, src/checks/zcl_aoc_check_08.clas.abap, src/checks/zcl_aoc_check_08.clas.testclasses.abap, src/checks/zcl_aoc_check_56.clas.abap
=> 08: check for CATCH SYSTEM-EXCEPTIONS

src/checks/zcl_aoc_check_75.clas.abap, src/checks/zcl_aoc_check_75.clas.testclasses.abap, src/checks/zcl_aoc_check_75.clas.xml
check for master language #571
=> check for master language #571

src/checks/zcl_aoc_check_56.clas.abap
56: ignore exceptions when checking paramters
=> 56: ignore exceptions when checking paramters

docs/_checks/78.md, src/checks/zcl_aoc_check_78.clas.abap, src/checks/zcl_aoc_check_78.clas.testclasses.abap, src/checks/zcl_aoc_check_78.clas.xml
=> check 78, #592

src/checks/zcl_aoc_check_58.clas.abap
=> 58: skip locally referenced parallel return method

src/checks/zcl_aoc_check_49.clas.abap, src/checks/zcl_aoc_check_49.clas.testclasses.abap
=> fixes #616

src/checks/zcl_aoc_check_51.clas.abap, src/checks/zcl_aoc_check_51.clas.testclasses.abap
=> Fix Check 51 - Open SQL - Escape host variables - false positive

docs/_checks/80.md, src/checks/zcl_aoc_check_80.clas.abap, src/checks/zcl_aoc_check_80.clas.testclasses.abap, src/checks/zcl_aoc_check_80.clas.xml
=> new check: space before colon

docs/_checks/81.md, src/checks/zcl_aoc_check_81.clas.abap, src/checks/zcl_aoc_check_81.clas.testclasses.abap, src/checks/zcl_aoc_check_81.clas.xml
check for missing space, close #90
=> check for missing space, close #90

src/parsing/zcl_aoc_structure.clas.abap, src/ui/zaoc_naming.fugr.lzaoc_namingf01.abap, src/utils/zaoc_count_classes_with_tests.prog.abap, src/utils/zaoc_orphaned_includes.prog.abap, src/utils/zaoc_tadir_changes.prog.abap
Didn't compile on 731 because of new syntax
=> Downport to 731

src/checks/zcl_aoc_check_49.clas.abap
=> close #399

docs/_checks/82.md, src/checks/zcl_aoc_check_82.clas.abap, src/checks/zcl_aoc_check_82.clas.testclasses.abap, src/checks/zcl_aoc_check_82.clas.xml, src/utils/zaoc_count_classes_with_tests.prog.abap
check pseudo comment placement #634
=> check pseudo comment placement #634

src/checks/zcl_aoc_check_45.clas.abap, src/checks/zcl_aoc_check_45.clas.locals_imp.abap
https://github.com/larshp/abapOpenChecks/issues/637
=> 45: new rule for line_exists

src/checks/zcl_aoc_check_40.clas.abap, src/checks/zcl_aoc_check_40.clas.testclasses.abap
=> Check 40 - check sy-subrc - fix false positive in IF/CASE-clauses

src/checks/zcl_aoc_check_27.clas.abap, src/checks/zcl_aoc_check_43.clas.abap, src/checks/zcl_aoc_check_45.clas.abap, src/checks/zcl_aoc_check_46.clas.abap, src/checks/zcl_aoc_check_56.clas.abap, src/checks/zcl_aoc_check_79.clas.abap, src/checks/zcl_aoc_super.clas.abap, src/checks/zcl_aoc_super.clas.testclasses.abap, src/utils/zcl_aoc_compiler.clas.abap, src/utils/zcl_aoc_compiler.clas.xml
separating compiler from super class
=> separating compiler from super class

src/checks/zcl_aoc_check_12.clas.abap, src/checks/zcl_aoc_check_12.clas.testclasses.abap
=> Check 12 - Specify SORT order - order before BY

src/parsing/zcl_aoc_boolean.clas.abap, src/parsing/zcl_aoc_boolean.clas.testclasses.abap
=> Fix ZCL_AOC_BOOLEAN `ref data( ... )`

src/checks/zcl_aoc_check_08.clas.abap, src/checks/zcl_aoc_check_08.clas.testclasses.abap
new operator: check if part of TYPE #658
=> new operator: check if part of TYPE

src/checks/zcl_aoc_super.clas.abap
skip findings in SSFO generated includes
=> skip findings in SSFO generated includes

docs/_checks/83.md, src/checks/zcl_aoc_check_83.clas.abap, src/checks/zcl_aoc_check_83.clas.testclasses.abap, src/checks/zcl_aoc_check_83.clas.xml
=> new check for unreferenced ddic objects

src/checks/zcl_aoc_check_51.clas.abap
=> Account for COUNT(*) in escape host vars check

src/checks/zcl_aoc_check_01.clas.abap, src/checks/zcl_aoc_check_22.clas.abap, src/parsing/zcl_aoc_structure.clas.abap
=> refactor ZCL_AOC_STRUCTURE

src/checks/zcl_aoc_check_69.clas.abap
constants naming, check 69, #679
=> constants naming, check 69, #679

docs/_checks/87.md, src/checks/zcl_aoc_check_87.clas.abap, src/checks/zcl_aoc_check_87.clas.testclasses.abap, src/checks/zcl_aoc_check_87.clas.xml
=> new check, dynpro overlaps

src/checks/zcl_aoc_check_69.clas.abap
check 69, handle nested BEGIN OF #684
=> check 69, handle nested BEGIN OF #684

src/checks/zcl_aoc_check_40.clas.abap, src/checks/zcl_aoc_check_40.clas.testclasses.abap
=> Check 40 - Check SY-SUBRC - does not find all errors

src/checks/zcl_aoc_super.clas.abap
I came across an issue when implementing a note. I got ATC findings in the changed code. The findings were reported in line 0. This is because the affected code was part of a macro and tokens in a macro always have row 0. Unfortunately the filter for findings in SAP standard code does not work with line 0.
SAP standard checks report findings in macros with the line number where the macro is called. I have adjusted the inform method to implement the same logic here.
Please note that this only works if parameter p_position is passed. Only a few of the abapOpenChecks do this (the ones I have adjusted for the checksum).
=> Macro handling

docs/_checks/90.md, src/checks/zcl_aoc_check_90.clas.abap, src/checks/zcl_aoc_check_90.clas.testclasses.abap, src/checks/zcl_aoc_check_90.clas.xml, src/checks/zcl_aoc_super_root.clas.abap
=> add check for constructor visibility

docs/_checks/92.md, src/checks/zcl_aoc_check_92.clas.abap, src/checks/zcl_aoc_check_92.clas.testclasses.abap, src/checks/zcl_aoc_check_92.clas.xml
Created abapOpenCheck Number 92 - I couldn't find anywhere if a unit test exists. Only if it is successfull. But if there is no unit test, SCI will accept this. This test should prevent this
=> Added Check number 92 ( with docs )

docs/_checks/05.md, docs/_checks/06.md, docs/_checks/09.md, docs/_checks/13.md, docs/_checks/14.md, docs/_checks/52.md, docs/_checks/80.md, src/checks/zcl_aoc_check_05.clas.abap, src/checks/zcl_aoc_check_06.clas.abap, src/checks/zcl_aoc_check_09.clas.abap, src/checks/zcl_aoc_check_13.clas.abap, src/checks/zcl_aoc_check_14.clas.abap, src/checks/zcl_aoc_check_28.clas.abap, src/checks/zcl_aoc_check_52.clas.abap, src/checks/zcl_aoc_check_80.clas.abap, src/checks/zcl_aoc_super.clas.abap
closes #703 
closes #704 
closes #705 
closes #706
=> RFC enable additional checks

docs/_checks/01.md, docs/_checks/02.md, docs/_checks/04.md, docs/_checks/06.md, docs/_checks/07.md, docs/_checks/08.md, docs/_checks/11.md, docs/_checks/13.md, docs/_checks/14.md, docs/_checks/16.md, docs/_checks/18.md, docs/_checks/28.md, docs/_checks/30.md, docs/_checks/43.md, docs/_checks/44.md, docs/_checks/45.md, docs/_checks/49.md, docs/_checks/70.md, docs/_checks/80.md, docs/_checks/90.md
closes https://github.com/larshp/abapOpenChecks/issues/713
=> Clean abap links

src/utils/zaoc_lines_tree.prog.abap, src/utils/zaoc_lines_tree.prog.xml, src/utils/zcl_aoc_util_programs.clas.abap
=> update lines program

src/checks/zcl_aoc_check_45.clas.abap, src/checks/zcl_aoc_check_45.clas.testclasses.abap
45, fix for central ATC, closes #728
=> 45, fix for central ATC

src/checks/zcl_aoc_check_27.clas.abap, src/checks/zcl_aoc_check_27.clas.testclasses.abap
=> 27, fix for central ATC

src/checks/zcl_aoc_super.clas.abap
=> buffer SCR_SRCID result

src/checks/zcl_aoc_check_26.clas.abap
try to get a bit better performance for check 26
=> try to get a bit better performance for check 26

src/checks/zcl_aoc_check_59.clas.testclasses.abap, src/parsing/zcl_aoc_boolean.clas.abap, src/parsing/zcl_aoc_boolean.clas.testclasses.abap
=> 59, add hex compare operators

abaplint.json, src/checks/zcl_aoc_check_26.clas.abap, src/checks/zcl_aoc_check_26.clas.testclasses.abap
=> check 26, bugfix

src/checks/zcl_aoc_check_24_result.clas.abap
inherit from cl_ci_result_root instead
=> inherit from cl_ci_result_root instead

abaplint.json, src/checks/zcl_aoc_check_59.clas.abap, src/checks/zcl_aoc_check_59.clas.testclasses.abap
skip some ASSERT constructs, fixes #760
=> skip some ASSERT constructs #760

docs/_checks/97.md, src/checks/zcl_aoc_check_97.clas.abap, src/checks/zcl_aoc_check_97.clas.xml
=> New Check 97 - Selection Screen Texts

src/checks/zcl_aoc_super_root.clas.abap
=> Refactor: scimessages SUPER

src/checks/zcl_aoc_check_12.clas.abap, src/checks/zcl_aoc_check_12.clas.xml
=> Refactor: scimessages CHECK 12

src/checks/zcl_aoc_check_13.clas.abap, src/checks/zcl_aoc_check_13.clas.xml
=> Refactor: scimessages CHECK 13

src/checks/zcl_aoc_check_14.clas.abap, src/checks/zcl_aoc_check_14.clas.xml
=> Refactor: scimessages CHECK 14

src/checks/zcl_aoc_check_16.clas.abap, src/checks/zcl_aoc_check_16.clas.xml
=> Refactor: scimessages CHECK 16

src/checks/zcl_aoc_check_17.clas.abap, src/checks/zcl_aoc_check_17.clas.xml
=> Refactor: scimessages CHECK 17

src/checks/zcl_aoc_check_19.clas.abap, src/checks/zcl_aoc_check_19.clas.xml
=> Refactor: scimessages CHECK 19

src/checks/zcl_aoc_check_20.clas.abap, src/checks/zcl_aoc_check_20.clas.xml
=> Refactor: scimessages CHECK 20

src/checks/zcl_aoc_check_23.clas.abap, src/checks/zcl_aoc_check_23.clas.xml
=> Refactor: scimessages CHECK 23

src/checks/zcl_aoc_check_24.clas.abap, src/checks/zcl_aoc_check_24.clas.xml
=> Refactor: scimessages CHECK 24

abaplint.json, src/checks/zcl_aoc_check_27.clas.abap, src/checks/zcl_aoc_check_27.clas.xml
=> Refactor: scimessages CHECK 27

abaplint.json, src/checks/zcl_aoc_check_28.clas.abap, src/checks/zcl_aoc_check_28.clas.xml
=> Refactor: scimessages CHECK 28

abaplint.json, src/checks/zcl_aoc_check_29.clas.abap, src/checks/zcl_aoc_check_29.clas.xml
=> Refactor: scimessages CHECK 29

abaplint.json, src/checks/zcl_aoc_check_30.clas.abap, src/checks/zcl_aoc_check_30.clas.xml
=> Refactor: scimessages CHECK 30

abaplint.json, src/checks/zcl_aoc_check_31.clas.abap, src/checks/zcl_aoc_check_31.clas.xml
=> Refactor: scimessages CHECK 31

abaplint.json, src/checks/zcl_aoc_check_32.clas.abap, src/checks/zcl_aoc_check_32.clas.xml
=> Refactor: scimessages CHECK 32

abaplint.json, src/checks/zcl_aoc_check_33.clas.abap, src/checks/zcl_aoc_check_33.clas.xml
=> Refactor: scimessages CHECK 33

src/checks/zcl_aoc_check_26.clas.abap, src/checks/zcl_aoc_check_26.clas.xml
=> Refactor: scimessages CHECK 26

src/checks/zcl_aoc_check_35.clas.abap, src/checks/zcl_aoc_check_35.clas.xml
=> Refactor: scimessages CHECK 35

src/checks/zcl_aoc_check_36.clas.abap, src/checks/zcl_aoc_check_36.clas.xml
=> Refactor: scimessages CHECK 36

src/checks/zcl_aoc_check_37.clas.abap, src/checks/zcl_aoc_check_37.clas.xml
=> Refactor: scimessages CHECK 37

src/checks/zcl_aoc_check_38.clas.abap, src/checks/zcl_aoc_check_38.clas.xml
=> Refactor: scimessages CHECK 38

abaplint.json, src/checks/zcl_aoc_check_39.clas.abap, src/checks/zcl_aoc_check_39.clas.xml
=> Refactor: scimessages CHECK 39

src/checks/zcl_aoc_check_34.clas.abap, src/checks/zcl_aoc_check_34.clas.xml
=> Refactor: scimessages CHECK 34

src/checks/zcl_aoc_check_40.clas.abap, src/checks/zcl_aoc_check_40.clas.xml
=> Refactor: scimessages CHECK 40

src/checks/zcl_aoc_check_41.clas.abap, src/checks/zcl_aoc_check_41.clas.xml
=> Refactor: scimessages CHECK 41

src/checks/zcl_aoc_check_42.clas.abap, src/checks/zcl_aoc_check_42.clas.xml
=> Refactor: scimessages CHECK 42

src/checks/zcl_aoc_check_44.clas.abap, src/checks/zcl_aoc_check_44.clas.xml
=> Refactor: scimessages CHECK 44

src/checks/zcl_aoc_check_43.clas.abap, src/checks/zcl_aoc_check_43.clas.xml
=> Refactor: scimessages CHECK 43

src/checks/zcl_aoc_check_45.clas.abap, src/checks/zcl_aoc_check_45.clas.xml
=> Refactor: scimessages CHECK 45

src/checks/zcl_aoc_check_46.clas.abap, src/checks/zcl_aoc_check_46.clas.xml
=> Refactor: scimessages CHECK 46

src/checks/zcl_aoc_check_47.clas.abap, src/checks/zcl_aoc_check_47.clas.xml
=> Refactor: scimessages CHECK 47

src/checks/zcl_aoc_check_48.clas.abap, src/checks/zcl_aoc_check_48.clas.xml
=> Refactor: scimessages CHECK 48

src/checks/zcl_aoc_check_49.clas.abap, src/checks/zcl_aoc_check_49.clas.xml
=> Refactor: scimessages CHECK 49

src/checks/zcl_aoc_check_50.clas.abap, src/checks/zcl_aoc_check_50.clas.xml
=> Refactor: scimessages CHECK 50

src/checks/zcl_aoc_check_51.clas.abap, src/checks/zcl_aoc_check_51.clas.xml
=> Refactor: scimessages CHECK 51

src/checks/zcl_aoc_check_52.clas.abap, src/checks/zcl_aoc_check_52.clas.xml
=> Refactor: scimessages CHECK 52

src/checks/zcl_aoc_check_55.clas.abap, src/checks/zcl_aoc_check_55.clas.xml
=> Refactor: scimessages CHECK 55

src/checks/zcl_aoc_check_57.clas.abap, src/checks/zcl_aoc_check_57.clas.xml
=> Refactor: scimessages CHECK 57

src/checks/zcl_aoc_check_58.clas.abap, src/checks/zcl_aoc_check_58.clas.xml
=> Refactor: scimessages CHECK 58

src/checks/zcl_aoc_check_59.clas.abap, src/checks/zcl_aoc_check_59.clas.xml
=> Refactor: scimessages CHECK 59

src/checks/zcl_aoc_check_60.clas.abap, src/checks/zcl_aoc_check_60.clas.xml
=> Refactor: scimessages CHECK 60

src/checks/zcl_aoc_check_61.clas.abap, src/checks/zcl_aoc_check_61.clas.xml
=> Refactor: scimessages CHECK 61

src/checks/zcl_aoc_check_75.clas.abap, src/checks/zcl_aoc_check_75.clas.xml
=> Refactor: scimessages CHECK 75

src/checks/zcl_aoc_check_62.clas.abap, src/checks/zcl_aoc_check_62.clas.xml
=> Refactor: scimessages CHECK 62

src/checks/zcl_aoc_check_63.clas.abap, src/checks/zcl_aoc_check_63.clas.xml
=> Refactor: scimessages CHECK 63

src/checks/zcl_aoc_check_64.clas.abap, src/checks/zcl_aoc_check_64.clas.xml
=> Refactor: scimessages CHECK 64

src/checks/zcl_aoc_check_65.clas.abap, src/checks/zcl_aoc_check_65.clas.xml
=> Refactor: scimessages CHECK 65

docs/_checks/53.md
Added cl_progress_indicator example, since it at first wasn't clear to me how to use this class instead of function module. SAPGUI_PROGRESS_INDICATOR.
=> Updated 53.md with example

src/checks/zcl_aoc_check_66.clas.abap, src/checks/zcl_aoc_check_66.clas.xml
=> Refactor: scimessages CHECK 66

src/checks/zcl_aoc_check_67.clas.abap, src/checks/zcl_aoc_check_67.clas.xml
=> Refactor: scimessages CHECK 67

src/checks/zcl_aoc_check_68.clas.abap, src/checks/zcl_aoc_check_68.clas.xml
=> Refactor: scimessages CHECK 68

src/checks/zcl_aoc_check_69.clas.abap, src/checks/zcl_aoc_check_69.clas.xml
=> Refactor: scimessages CHECK 69

src/checks/zcl_aoc_check_71.clas.abap, src/checks/zcl_aoc_check_71.clas.xml
=> Refactor: scimessages CHECK 71

src/checks/zcl_aoc_check_72.clas.abap, src/checks/zcl_aoc_check_72.clas.xml
=> Refactor: scimessages CHECK 72

src/checks/zcl_aoc_check_73.clas.abap, src/checks/zcl_aoc_check_73.clas.xml
=> Refactor: scimessages CHECK 73

src/checks/zcl_aoc_check_74.clas.abap, src/checks/zcl_aoc_check_74.clas.xml
=> Refactor: scimessages CHECK 74

src/parsing/zcl_aoc_parser.clas.abap
As said in Issue #764 - removed usage of statics and made them to class-data.
=> Removed Statics from ZCL_AOC_PARSER=>GET_XML

src/checks/zcl_aoc_check_76.clas.abap, src/checks/zcl_aoc_check_76.clas.xml
=> Refactor: scimessages CHECK 76

src/checks/zcl_aoc_check_77.clas.abap, src/checks/zcl_aoc_check_77.clas.xml
=> Refactor: scimessages CHECK 77

src/checks/zcl_aoc_check_78.clas.abap, src/checks/zcl_aoc_check_78.clas.xml
=> Refactor: scimessages CHECK 78

src/checks/zcl_aoc_check_79.clas.abap, src/checks/zcl_aoc_check_79.clas.xml
=> Refactor: scimessages CHECK 79

src/checks/zcl_aoc_check_80.clas.abap, src/checks/zcl_aoc_check_80.clas.xml
=> Refactor: scimessages CHECK 80

src/checks/zcl_aoc_check_81.clas.abap, src/checks/zcl_aoc_check_81.clas.xml
=> Refactor: scimessages CHECK 81

src/checks/zcl_aoc_check_82.clas.abap, src/checks/zcl_aoc_check_82.clas.xml
=> Refactor: scimessages CHECK 82

src/checks/zcl_aoc_check_83.clas.abap, src/checks/zcl_aoc_check_83.clas.xml
=> Refactor: scimessages CHECK 83

src/checks/zcl_aoc_check_84.clas.abap, src/checks/zcl_aoc_check_84.clas.xml
=> Refactor: scimessages CHECK 84

src/checks/zcl_aoc_check_86.clas.abap, src/checks/zcl_aoc_check_86.clas.xml
=> Refactor: scimessages CHECK 86

src/checks/zcl_aoc_check_87.clas.abap, src/checks/zcl_aoc_check_87.clas.xml
=> Refactor: scimessages CHECK 87

src/checks/zcl_aoc_check_88.clas.abap, src/checks/zcl_aoc_check_88.clas.xml
=> Refactor: scimessages CHECK 88

src/checks/zcl_aoc_check_92.clas.abap, src/checks/zcl_aoc_check_92.clas.xml
=> Refactor: scimessages CHECK 92

src/checks/zcl_aoc_check_93.clas.abap, src/checks/zcl_aoc_check_93.clas.xml
=> Refactor: scimessages CHECK 93

src/checks/zcl_aoc_check_94.clas.abap, src/checks/zcl_aoc_check_94.clas.xml
=> Refactor: scimessages CHECK 94

src/checks/zcl_aoc_check_95.clas.abap
=> Refactor: scimessages CHECK 95

src/checks/zcl_aoc_check_96.clas.abap, src/checks/zcl_aoc_check_96.clas.xml
=> Refactor: scimessages CHECK 96

src/checks/zcl_aoc_check_97.clas.abap, src/checks/zcl_aoc_check_97.clas.xml
=> Refactor: scimessages CHECK 97

src/checks/zcl_aoc_check_22.clas.abap, src/checks/zcl_aoc_check_22.clas.xml
=> Refactor: scimessages CHECK 22

src/checks/zcl_aoc_check_56.clas.abap, src/checks/zcl_aoc_check_56.clas.xml
=> Refactor: scimessages CHECK 56

src/checks/zcl_aoc_check_85.clas.abap, src/checks/zcl_aoc_check_85.clas.xml
=> Refactor: scimessages CHECK 85

docs/_checks/69.md, src/checks/zcl_aoc_check_69.clas.xml, src/checks/zcl_aoc_check_76.clas.testclasses.abap
=> Change Name of Check 69

src/checks/zcl_aoc_check_31.clas.abap, src/checks/zcl_aoc_check_69.clas.abap, src/checks/zcl_aoc_check_69.clas.xml, src/checks/zcl_aoc_super.clas.abap, src/utils/zcl_aoc_util_reg_atc_namespace.clas.abap
downport, registered namespaces #789
@MiLiCLN
=> downport, registered namespaces #789

src/checks/zcl_aoc_check_40.clas.abap, src/checks/zcl_aoc_check_48.clas.abap, src/checks/zcl_aoc_check_69.clas.abap, src/checks/zcl_aoc_super.clas.abap, src/checks/zcl_aoc_super_root.clas.abap
=> Fix Broken Texts

src/checks/zcl_aoc_check_99.clas.abap, src/checks/zcl_aoc_check_99.clas.testclasses.abap, src/checks/zcl_aoc_check_99.clas.xml
Issue #201 
I focused on CASE to begin with, and will do SWITCH a bit later.
I thought I'd create a separate PR for the documentation once I've gotten feedback on the code.
=> Number of WHENs in CASE

docs/_checks/94.md, src/checks/zcl_aoc_check_94.clas.abap
=> Check 94 RFC enabled

src/checks/zcl_aoc_super.clas.abap
Skip automatically generated objects
=> Skip generated objects

docs/_checks/45.md, src/checks/zcl_aoc_super.clas.abap, src/checks/zcl_aoc_super_root.clas.abap
The description for the line_exists( ) expression does not exist in the documentation.
=> Add description to line_exists( )

docs/_checks/99.md
Added link to SAP's styleguide
=> Update 99.md with link to SAP's styleguide

docs/_checks/45.md
=> CONDENSE and NO-GAPS

src/checks/zcl_aoc_check_53.clas.abap
=> Check 53, fix activation check for binary conversions (fixes #930)

src/utils/zcl_aoc_util_reg_atc_namespace.clas.abap
=> Consider SAP Namespace /0SAP/

docs/_checks/69.md
=> 69.md - Add multiple values

src/checks/zcl_aoc_check_69.clas.abap
=> CHECK_69: Enable all occurrences of [:type:]

src/checks/zcl_aoc_check_31.clas.abap
Add SLIN test descriptionto check message (same behavior as standard "Extended Program Check (SLIN)").
Add a new line to text message with SLIN code key.
I used string expression but it matches the 740sp2 prerequisite.
=> Check 31 - Issue #960 add SLIN test description to check message

src/checks/zcl_aoc_check_98.clas.abap, src/checks/zcl_aoc_check_98.clas.testclasses.abap
Fix https://github.com/larshp/abapOpenChecks/issues/893
=> Check 98 - Issue #893

src/checks/zcl_aoc_check_45.clas.abap, src/checks/zcl_aoc_check_45.clas.testclasses.abap
=> CHECK_45 - CONCATENATE RESPECTING BLANKS

docs/_checks/38.md, src/checks/zcl_aoc_check_38.clas.abap, src/checks/zcl_aoc_check_38.clas.testclasses.abap
Select Statement UP TO n ROWS  should pass this check.
=> Check 38 Exception for UP TO n ROWS Statement

src/checks/zcl_aoc_super.clas.abap
=> checksum fixes

src/checks/zcl_aoc_check_33.clas.abap, src/utils/zcl_aoc_util_reg_atc_namespace.clas.abap
=> Check 33 - Also allow own registered namespace

docs/_checks/101.md
=> fix 101.md

src/checks/zcl_aoc_check_95.clas.abap
=> Check 95 - Object / Class member access - Invalid results #996

src/checks/zcl_aoc_check_45.clas.abap
=> zcl_aoc_check_45.clas.abap[169, 5] - Modification of SY field #994

abaplint.json, src/checks/zcl_aoc_check_92.clas.abap, src/parsing/zcl_aoc_parser.clas.abap, src/utils/zaoc_clearance.prog.abap, src/utils/zaoc_clones.prog.abap, src/utils/zaoc_date_analysis.prog.abap, src/utils/zaoc_open_transport.prog.abap
=> remove unnecessary self references

src/checks/zcl_aoc_check_31.clas.abap
=> CHECK_31: fix SLIN Code display

src/checks/zcl_aoc_check_27.clas.abap, src/checks/zcl_aoc_check_27.clas.testclasses.abap
=> Check 27 - fix false positive: exit from step-loop

src/checks/zcl_aoc_check_69.clas.abap
=> Check 69: "unable to resolve" FuGr with customer include

src/checks/zcl_aoc_check_69.clas.abap
First attempt to fix the issue.
Closes #935
=> Check 69 - Determine exception type #935

src/checks/zcl_aoc_check_22.clas.abap, src/checks/zcl_aoc_check_31.clas.abap, src/checks/zcl_aoc_check_56.clas.abap, src/checks/zcl_aoc_check_58.clas.abap, src/checks/zcl_aoc_check_59.clas.abap, src/checks/zcl_aoc_check_69.clas.abap, src/checks/zcl_aoc_check_70.clas.abap, src/checks/zcl_aoc_check_95.clas.abap
More adjustments for v731.
I change all I could, but check 64 cannot be adjusted
=> Syntax v731

src/checks/zcl_aoc_super.clas.abap
=> Unit testing, fix checksum problems

src/checks/zcl_aoc_check_04.clas.testclasses.abap
=> 04: fix unit test

src/checks/zcl_aoc_check_01.clas.abap
rollback changes fromhttps://github.com/larshp/abapOpenChecks/pull/1022, it unit tests
see #1031
=> 01 unit test: rollback syntax changes

src/checks/zcl_aoc_super.clas.abap
=> TADIR select performance

README.md
closes #1040 
Possible reduction of issues during installation such as:
#1029
=> extend README -> using latest abapgit

src/parsing/zcl_aoc_parser.clas.abap
Fix for unfilled table SSYNTAXSTRUCTURE
=> Fix for unfilled table SSYNTAXSTRUCTURE

README.md
=> add Steampunk link

src/checks/zcl_aoc_check_79.clas.abap
The check for "CLEAR ... WITH" was added as permissible. In doing so, the condition according to "think positive" was reversed.
=> Added CLEAR WITH

src/checks/zcl_aoc_check_59.clas.abap
fixing before https://github.com/abaplint/abaplint/pull/2435
=> workaround empty WHEN

src/parsing/zcl_aoc_parser.clas.abap
=> ZCL_AOC_PARSER ssyntaxstructure

docs/_checks/100.md, docs/_checks/101.md
The links did not work
- Check 100
- Check 101
=> Repair Link

src/checks/zcl_aoc_check_96.clas.abap
=> bugfix, check 96

src/checks/zcl_aoc_check_101.clas.abap, src/checks/zcl_aoc_check_101.clas.testclasses.abap
Prefer IS NOT to NOT IS - IF NOT methodcall(). - false positive
=> Check 101 - issue  #1054

src/checks/zcl_aoc_check_40.clas.abap, src/checks/zcl_aoc_check_40.clas.testclasses.abap
I deleted the second space in the search pattern as I proposed in the issue.
=> #1083 040-Doesn't recognize swap of lhs and rhs

docs/_checks/79.md
=> docs: check 79 is not rfc enabled

src/checks/zcl_aoc_check_06.clas.abap, src/checks/zcl_aoc_check_35.clas.abap, src/checks/zcl_aoc_check_43.clas.abap, src/checks/zcl_aoc_check_44.clas.abap, src/checks/zcl_aoc_check_58.clas.abap, src/checks/zcl_aoc_check_61.clas.abap, src/checks/zcl_aoc_check_84.clas.abap, src/checks/zcl_aoc_check_86.clas.abap, src/checks/zcl_aoc_check_88.clas.abap, src/checks/zcl_aoc_check_96.clas.abap, src/collectors/zcl_aoc_embedded_packages.clas.abap, src/dependencies/zcl_aoc_dependencies.clas.abap, src/parsing/zcl_aoc_parser.clas.abap, src/utils/zaoc_clearance.prog.abap, src/utils/zaoc_count_classes_with_tests.prog.abap, src/utils/zaoc_line_length.prog.abap, src/utils/zaoc_method_length.prog.abap, src/utils/zaoc_open_transport.prog.abap, src/utils/zaoc_orphaned_includes.prog.abap, src/utils/zaoc_tadir_checks.prog.abap, src/utils/zcl_aoc_util_programs.clas.abap, src/utils/zcl_aoc_util_reg_atc_namespace.clas.abap
Ref:https://github.com/larshp/abapOpenChecks/issues/1073
=> add Order by where applicable

src/checks/zcl_aoc_check_01.clas.abap, src/checks/zcl_aoc_check_01.clas.testclasses.abap
related pr: https://github.com/larshp/abapOpenChecks/pull/1090
closes #1049
=> fix_if_in_if

src/checks/zcl_aoc_check_69.clas.abap
Add type_kind_enum and type_kind_ddic_entity
close #1058
=> CHECK_69: Add missing type_kinds

src/checks/zcl_aoc_check_69.clas.abap
=> Check_69: Add missing FM IDOC-Signature for Output

src/checks/zcl_aoc_check_45.clas.abap, src/checks/zcl_aoc_check_45.clas.xml
Correct small syntax error for `corresponding` statement.
=> Check 45: update docs

src/checks/zcl_aoc_check_63.clas.abap
=> Check_63: correct scimessage number

src/checks/zcl_aoc_check_83.clas.abap
=> CHECK_83: Fix not finding DDIC in function module signature

src/parsing/zcl_aoc_boolean.clas.abap
=> Fix boolean parser error "IS NOT INSTANCE OF"

docs/_checks/103.md, src/checks/zcl_aoc_check_103.clas.abap, src/checks/zcl_aoc_check_103.clas.testclasses.abap, src/checks/zcl_aoc_check_103.clas.xml
=> Check 103 - SELECT on table with replacement obj

src/checks/zcl_aoc_check_103.clas.abap, src/checks/zcl_aoc_check_103.clas.locals_imp.abap
=> 103 update quick fix with as

src/checks/zcl_aoc_check_47.clas.abap, src/checks/zcl_aoc_check_47.clas.testclasses.abap
- limited check to CALL FUNCTION
- inverted check to positive formulation (easier readability)
- removed now obsolete variables
=> #1148 limit check to CALL FUNCTION

docs/_checks/71.md
=> Documentation check 71

docs/_checks/58.md
To me it was not obvious what "Skip CCAU" meant. I tried to clarify it.
=> Clarify meaning of "Skip CCAU" in check 58

src/checks/zcl_aoc_super.clas.abap
Fixes https://github.com/larshp/abapOpenChecks/issues/1160
=> Generate checksum also for lines with comments

src/checks/zcl_aoc_check_08.clas.abap, src/checks/zcl_aoc_check_08.clas.testclasses.abap
Specifically for obsolete operators, but could be expanded.
=> Check 08: Exempt AMDP

docs/_checks/104.md, src/checks/zcl_aoc_check_104.clas.abap, src/checks/zcl_aoc_check_104.clas.locals_def.abap, src/checks/zcl_aoc_check_104.clas.testclasses.abap, src/checks/zcl_aoc_check_104.clas.xml, src/checks/zcl_aoc_scan.clas.abap, src/utils/zcl_aoc_local_system.clas.abap, src/utils/zcl_aoc_local_system.clas.xml, src/utils/zif_aoc_system.intf.abap, src/utils/zif_aoc_system.intf.xml
This adds check 104. Please see the documentation for details on the motivation.
=> Add check 104 for missing local RFC function mod.
