larshp/abapOpenChecks

- src/checks/zcl_aoc_check_56.clas.abap
In case a parameter should be reported for an abstract method, reading the method include will fail. In this case the inform must be called as it is for interfaces.
> Avoid dumps when method is abstract

- src/checks/zcl_aoc_check_71.clas.abap
- src/checks/zcl_aoc_check_71.clas.testclasses.abap
- src/checks/zcl_aoc_check_71.clas.xml
New check for using statement :
message id sy-msgid type sy-msgty number sy-msgno with sy-msgv1 sy-msgv2 sy-msgv3 sy-msgv4.
It cause dumps when run after some FM that do not set system variables.
> Check 71 MESSAGE using SY-VARIABLES

- src/checks/zcl_aoc_check_56.clas.abap
This check has two parameters in customizing but it was not using it at all. I've added two lines to respect the parameters.
> Correction to CHECK_56

- src/checks/zcl_aoc_check_27.clas.abap
- src/checks/zcl_aoc_check_27.clas.testclasses.abap
It's not the nicest approach i could think of, but at least it fixes the false positive.
fix #308
> Check 27 - Last statement is obsolet - clear is okay if it is the parameter in a form

- src/checks/zcl_aoc_check_63.clas.abap
check 63: do not report error for inactive object
> check 63: do not report error for inactive object

- docs/_checks/85.md
- src/checks/zcl_aoc_check_85.clas.abap
- src/checks/zcl_aoc_check_85.clas.testclasses.abap
- src/checks/zcl_aoc_check_85.clas.xml
- src/checks/zcl_aoc_unit_test.clas.abap
It's still work in process, because:
- I don't know how to write proper unit tests for this check because of the use of `cl_abap_compiler`
- string templates can't be detected because `get_full_name_for_position` of `cl_abap_compiler` returns an exception
This check runs, if fixed point arithmetic is not active.
If you can activate it safely, it will return the configured error type.
If you can't activate it safely, it will return info messages.
I used this program to test this check (includes results of check):
https://gist.github.com/pcf0/d184e57c1f4d0aa64f9217446bd880c5
closes #665
> New Check: Activate fixed point arithmetic

- src/checks/zcl_aoc_check_45.clas.abap
- src/checks/zcl_aoc_check_45.clas.testclasses.abap
@larshp the fix you suggested works.
I also found another statement which can't be fixed: [`CREATE OBJECT oref AREA HANDLE handle`](https://help.sap.com/doc/abapdocu_750_index_htm/7.50/en-US/abapcreate_object_area_handle.htm)
fix #261
> Check 45 - Use NEW abc( ) expression - non-class-based exceptions

- src/checks/zcl_aoc_check_07.clas.abap
CALL METHOD OF is used for OLE (MS Office integration). It is still valid and therefore should not be detected as finding.
> Fix for CALL METHOD OF

- README.md
Just updated the menu path. It's not in "goto", rather in "Code Inspector".
> Update of SCI menu path in README.md

- src/checks/zcl_aoc_check_02.clas.abap
- src/checks/zcl_aoc_check_02.clas.xml
- src/checks/zcl_aoc_check_03.clas.abap
- src/checks/zcl_aoc_check_03.clas.xml
- src/checks/zcl_aoc_check_07.clas.abap
- src/checks/zcl_aoc_check_07.clas.xml
- src/checks/zcl_aoc_check_08.clas.abap
- src/checks/zcl_aoc_check_08.clas.xml
- src/checks/zcl_aoc_check_10.clas.abap
- src/checks/zcl_aoc_check_10.clas.xml
- src/checks/zcl_aoc_check_11.clas.abap
- src/checks/zcl_aoc_check_11.clas.xml
- src/checks/zcl_aoc_check_15.clas.abap
- src/checks/zcl_aoc_check_15.clas.xml
- src/checks/zcl_aoc_check_18.clas.abap
- src/checks/zcl_aoc_check_18.clas.xml
- src/checks/zcl_aoc_check_21.clas.abap
- src/checks/zcl_aoc_check_21.clas.xml
- src/checks/zcl_aoc_check_53.clas.abap
- src/checks/zcl_aoc_check_53.clas.xml
- src/checks/zcl_aoc_check_54.clas.abap
- src/checks/zcl_aoc_check_54.clas.xml
- src/checks/zcl_aoc_check_89.clas.abap
- src/checks/zcl_aoc_check_91.clas.abap
- src/checks/zcl_aoc_super.clas.abap
As discussed in https://github.com/larshp/abapOpenChecks/pull/692 and https://github.com/larshp/abapOpenChecks/issues/698, table scimessages should be filled in the constructor. This table is used to evaluate the texts for findings.
This commit includes the necessary changes in class zcl_aoc_super and adjusts a few checks.
> Fill table scimessages in constructor

- src/checks/zcl_aoc_check_45.clas.abap
Fixed spelling error (concate_lines_of( ) => concat_lines_of( ))
> Update zcl_aoc_check_45.clas.abap spelling error

- src/checks/zcl_aoc_check_40.clas.abap
- src/checks/zcl_aoc_check_40.clas.testclasses.abap
I indentified and fixed two problems:
1. if you have an `ASSERT sy-subrc = 0` it's allright. But if you have an `IF sy-subrc = 0.` then the `lv_stack` is increased first, which means that the condition in the `LOOP AT lt_stack` is not fulfilled.
2. the `inform` is not called if the last statement is a `READ TABLE`, `ENDIF` or `ENDCASE`
fix #767
> Check 40 - Check SY-SUBRC - false positive check with if

- src/checks/zcl_aoc_check_27.clas.abap
- src/checks/zcl_aoc_check_27.clas.testclasses.abap
Check 27 was not able to handle inline declarations. I added a unit test for this and also provided a solution.
> Adjusted check 27 to handle inline declarations

- docs/_checks/41.md
- docs/_checks/42.md
- docs/_checks/78.md
- docs/_checks/79.md
- docs/_checks/80.md
> Add rudimentary description to empty docs

- src/utils/zcl_aoc_util_reg_atc_namespace.clas.abap
For Z objects function TRINT_GET_NAMESPACE returns /0CUST/ namespace
> Customer namespace /0CUST/ for Z objects

- src/checks/zcl_aoc_check_06.clas.abap
Skip Function Group objects generated
I identify them because they have editor lock flag set and last change was made by user SAP*
> Issue #897 check 06   pretty printer for function modules

- src/utils/zaoc_wrapper.fugr.xml
- src/utils/zaoc_wrapper.fugr.zaoc_obj_doku_get_xstring_rfc.abap
Parameter is never supplied and optional below 750, but does not exist above 750
closes #1007 
Should be tested  for 702 (is the `version` parameter optional there as well?)
> Check 89: Remove Version Parameter in RFC-Function Module

- src/checks/zcl_aoc_check_69.clas.abap
There was an error in PR #1023.
The parameters of a method were detected as locals
> Check 069 - determine method types

- src/parsing/zcl_aoc_boolean.clas.abap
infinite loop fix #1024 
There is infinite loop in method `remove_method_calls` caused by changing mt_tokens in method `replace`
> infinite loop fix

- src/parsing/zcl_aoc_parser.clas.abap
Fixes unit test failure of check 14 reported in #1031.
The issue is non-deterministically reproducible since the SELECT did not specify any order and so whether or not the problem occurs depends on the order in which entries with the same rule name but different proglang values are returned from the database.
> Ignore BDL syntax in parser

- docs/_checks/45.md
- src/checks/zcl_aoc_check_45.clas.abap
- src/checks/zcl_aoc_check_45.clas.locals_def.abap
- src/checks/zcl_aoc_check_45.clas.locals_imp.abap
- src/checks/zcl_aoc_check_45.clas.testclasses.abap
- src/checks/zcl_aoc_check_45.clas.xml
if version >= v740sp08, use BASE with CORRESPONDING
if using CORRESPONDING without BASE addition, it will only have the same effect as MOVE-CORRESPONDING if the target is initial
change scan message to reflect this
closes #1019
> modify corresponding scan message

- src/checks/zcl_aoc_check_69.clas.abap
CP instead of CS.
It might be worth considering testing this via a REGEX and checking if the conversion exit name has the correct length. The current contains pattern statement will not inforce this.
See issue #1046.
> Conversion exits were not being skipped

- src/checks/zcl_aoc_check_15.clas.abap
- src/checks/zcl_aoc_check_15.clas.testclasses.abap
calling AMDP methods in AMDP methods also start with CALL. But those are not kernel calls.
> #1067 015-ignore AMDP method calls in AMDP methods

- src/checks/zcl_aoc_check_06.clas.abap
Validate pretty printer settings only for dialog users (type A). This allows check to be skipped for CI type users which are not able to login and configure settings.
https://github.com/larshp/abapOpenChecks/issues/1104
> Check 06: Validate pretty printer settings only for dialog users

- src/checks/zcl_aoc_check_06.clas.abap
- src/checks/zcl_aoc_check_06.clas.testclasses.abap
Fixes remaining issues mentioned in https://github.com/larshp/abapOpenChecks/issues/897.
Ignores the first line of function modules and function pool definitions due to auto formatting that gets applied.
> Check 06: Ignore FM and Function Pool definitions

- src/checks/zcl_aoc_check_34.clas.abap
- src/checks/zcl_aoc_check_34.clas.testclasses.abap
When ignoring comments for check 34 the current logic always counts 1 line less than there is in the code.
`lv_comment_lines = lv_comment_lines + <ls_statement>-to`
Example: Single line comment starts and ends in line 43 -> 0 comments
> Check 34 ignores single line comments

- docs/_checks/102.md
- src/checks/zcl_aoc_check_102.clas.abap
- src/checks/zcl_aoc_check_102.clas.locals_def.abap
- src/checks/zcl_aoc_check_102.clas.locals_imp.abap
- src/checks/zcl_aoc_check_102.clas.testclasses.abap
- src/checks/zcl_aoc_check_102.clas.xml
- src/checks/zcl_aoc_scan.clas.abap
This new check finds logic utilizing the value from `SY-SYSID`. 
I'm currently preparing for a system migration, so the name of the system will be different from before. I want to use this check to fix potential errors where logic is coupled to a specific system name.
> Add check 102 to detect `SY-SYSID` usage

- docs/_layouts/default.html
The links in the documentation still point to the `master` branch instead of the `main` branch. This works, but always displays the message "Branch master was renamed to main.".
This pull request should fix both the "Improve this page" and the "CODE" button from the check pages.
> Change documentation links from master to main

- src/checks/zcl_aoc_scan.clas.abap
- src/utils/zcl_aoc_sy_variable_analyzer.clas.abap
- src/utils/zcl_aoc_sy_variable_analyzer.clas.testclasses.abap
This pull request adds capabilities to the SY variable analyzer to correctly classify the use of MOVE as either assigning to a variable or overriding the original value.
> CHECK_102: Correctly classify usage of MOVE

- src/checks/zcl_aoc_check_47.clas.abap
I did not see the unit test failing before. Reverted most of changes and still left the restriction for CALL FUNCTION in place. Added a comment on why it is solved this way.
> Check-47: DESTINATION parameter not recognized any more #1148

- docs/_checks/60.md
The formatting is broken on https://docs.abapopenchecks.org/checks/60/ even though it looks correct in the preview on GitHub. I hope that an escape character will help.
> Documentation for check 60

- src/checks/zcl_aoc_check_57.clas.abap
- src/checks/zcl_aoc_check_76.clas.abap
- src/checks/zcl_aoc_super.clas.abap
Add stable checksum calculation to checks 57 and 76. Fixes https://github.com/larshp/abapOpenChecks/issues/1162
> Add stable checksum calculation to checks 57 and 76

- src/checks/zcl_aoc_check_57.clas.abap
Check 57 is based on the statement table io_scan->build_statements( ) instead of io_scan->statements. Therefore we cannot use the index of the line in the table returned by build_statements( ) but we need to use the field "index" in that table to calculate the checksum.
Fixes in issue introduced with https://github.com/larshp/abapOpenChecks/pull/1163 that enabled checksum calculation (https://github.com/larshp/abapOpenChecks/issues/1162).
> Correct position for checksum calculation in check 57

- src/checks/zcl_aoc_check_08.clas.abap
- src/checks/zcl_aoc_check_08.clas.testclasses.abap
- src/checks/zcl_aoc_check_15.clas.abap
- src/checks/zcl_aoc_check_15.clas.testclasses.abap
- src/checks/zcl_aoc_check_20.clas.abap
- src/checks/zcl_aoc_check_20.clas.testclasses.abap
- src/checks/zcl_aoc_check_41.clas.abap
Simpler solution to skip AMDP methods only (not entire class) for checks 8, 15, 20, & 41. Skip processing for statements with type E (native sql).
This also improves changes made in #1166 & #1068
> Various checks: exempt AMDP

- docs/_checks/104.md
I made a small oversight in the documentation last time, sorry
> Fix error in documentation for check 104

- src/checks/zcl_aoc_check_104.clas.abap
- src/checks/zcl_aoc_check_104.clas.testclasses.abap
- src/checks/zcl_aoc_scan.clas.abap
If a parameter, an exception or a variable is called `destination`, then the function module call was falsely detected as using RFC.
> CHECK_104: Fix detection of DESTINATION keyword

- src/checks/zcl_aoc_check_69.clas.abap
Fix for #1177 
Tested with:
```abap
TYPES: BEGIN OF ENUM ty_enum,
one,
two,
END OF ENUM ty_enum.
TYPES: BEGIN OF ENUM ty_enum_structure STRUCTURE enum_test,
one,
two,
END OF ENUM ty_enum_structure STRUCTURE enum_test.
TYPES: BEGIN OF enum,
one TYPE i,
two TYPE i,
END OF enum.
```
> Determine correct type name for ENUM types
